# Generated by Django 4.0.5 on 2022-10-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0003_remove_orderinfo_phoneadd_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание:'),
        ),
    ]
