# Generated by Django 4.0.5 on 2022-10-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=2500, verbose_name='Отзыв'),
        ),
    ]
