# Generated by Django 4.0.5 on 2022-10-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0004_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_key',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='payment',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Город:'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='postal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс:'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя Фамилия:'),
        ),
    ]
