# Generated by Django 4.0.5 on 2022-10-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0005_remove_order_order_key_remove_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер телефона'),
        ),
    ]
