# Generated by Django 4.0.5 on 2022-10-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0006_alter_customer_email_alter_customer_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес:'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Город:'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Имя Фамилия:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер телефона:'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс:'),
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
