# Generated by Django 4.0.5 on 2022-10-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0007_order_address_order_city_order_name_order_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='novinki',
        ),
        migrations.RemoveField(
            model_name='product',
            name='popularnye',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Имя клиента: '),
            preserve_default=False,
        ),
    ]
