# Generated by Django 4.0.5 on 2022-10-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0010_product_gender_product_category_product_typep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментарии', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Gender',
            new_name='gender',
        ),
    ]
