# Generated by Django 4.0.5 on 2022-11-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0011_alter_comment_options_rename_gender_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='female',
            field=models.BooleanField(default=False, verbose_name='Женщина'),
        ),
        migrations.AddField(
            model_name='comment',
            name='male',
            field=models.BooleanField(default=False, verbose_name='Мужчина'),
        ),
    ]
